### ISSUE TITLE
React Ape 0.1.0  🔥🐒 

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/react-ape#20]
Related #16 #19 

# Docs

- [ ] Start sections on documentation (ref #18) 
  - [ ] `react-ape-boilerplate` 
  - [ ] "APIs" Section (ref #18) 
      - [ ] List of View props (https://facebook.github.io/react-native/docs/view-style-props)
      - [ ] List of Image props (https://facebook.github.io/react-native/docs/image-style-props)
  - [x] "Components" Section (ref #18) 
  - [x] "Contributing" Section (ref #22) 
  - [x] Work on a way to render react-ape in Docusaurus
- [x] Add React Ape logo 95d5b1d832087f1e1a3d4966fa0237d157140687
- [x] Publish site (WIP)

# Components

- [ ] `<SectionList/>` https://facebook.github.io/react-native/docs/sectionlist (#33)
- [ ] `<Button/>` https://facebook.github.io/react-native/docs/button
- [ ] `<TextInput/>` https://facebook.github.io/react-native/docs/textinput
- [ ] `<Picker/>` https://facebook.github.io/react-native/docs/picker
- [ ] `<Slider/>`  https://facebook.github.io/react-native/docs/slider
- [ ] `<Modal/>` https://facebook.github.io/react-native/docs/modal

# APIs

- [x] `dimensions` #28 

#  Core

- [x] Virtual Canvas algorithm #21  ⚡️⚡️⚡️ 
- [ ] Allows to inspect using React DevTools 💯(dependent of #21)

**Comment by raphamorim** [comment]
Additional item for future release (0.1.x): 
- [ ] Fix layout organization. React Ape is rendering Views based in `position: absolute` by default. Should fix it for `position: relative` by default (need to change render algorithm to support that)

**Comment by raphamorim** [comment]
Created the milestone to track those items: https://github.com/raphamorim/react-ape/milestone/1
Closing this issue.
